trigger CreateDatesForAllPeople on Possible_Date__c (after insert) {

    Possible_Date__c[] pds = Trigger.new;
    for(Possible_Date__c pd: pds)
    {
        //first, get a handle to the request
        ResourceRequest__c rr = [Select Id, Name from ResourceRequest__c where Id = :pd.Resource_Request__c LIMIT 1];        

        //now, get the list of all assignments
        Resource_Assignment__c[] ras = [Select Id, Resource_Request__c from Resource_Assignment__c where Resource_Request__c = :rr.Id];
        
        //for each of these, add a new resource availability with status of Not Specified
               for(Resource_Assignment__c ra : ras)
        {
            Resource_Availability__c rav = new Resource_Availability__c();
            rav.Name = 'Autogenerated';
            rav.Availability__c = 'Not Specified';
            rav.Possible_Date__c = pd.Id;
            rav.Resource_Assignment__c = ra.Id;
            insert rav;
                        
        }
    }
}