trigger SetupFromRequest on Resource_Assignment__c (after insert) {



    Resource_Assignment__c[] assigns = Trigger.new;
    for(Resource_Assignment__c assign: assigns)
    {
        
        //first, get a handle to the request
        ResourceRequest__c rr = [Select Id, Name from ResourceRequest__c where Id = :assign.Resource_Request__c LIMIT 1];        

        //now, get the list of all possible dates
        
        Possible_Date__c[] pds = [Select Id from Possible_Date__c  where Resource_Request__c = :rr.Id ];
        
        //now, for each possible date, we need to create an availability
        for(Possible_Date__c pd: pds)
        {
            Resource_Availability__c rav = new Resource_Availability__c();
            rav.Name = 'Autogenerated';
            rav.Availability__c = 'Not Specified';
            rav.Possible_Date__c = pd.Id;
            rav.Resource_Assignment__c = assign.Id;
            insert rav;        
        }
   
   
    }

}