trigger UpdateStatusForAllPossibles on Possible_Date__c (after update, after insert) {

    Possible_Date__c[] pds = Trigger.new;
    for(Possible_Date__c pd: pds)
    {
        if(pd.Status__c == 'Selected')
        {
            //first, get a handle to the request
            ResourceRequest__c rr = [Select Id, Name from ResourceRequest__c where Id = :pd.Resource_Request__c LIMIT 1];        
    
            //now, get the list of all possible dates
            Possible_Date__c [] allPDs = [Select Id, Resource_Request__c, Status__c from Possible_Date__c where Resource_Request__c = :rr.Id];
            
            //for each of these, add 
            for(Possible_Date__c otherPD : allPDs)
            {
                if(otherPD.Status__c == 'Possible')
                {
                    otherPD.Status__c = 'Not Selected';
                    update otherPD;
                }
                /*
            
                Resource_Availability__c rav = new Resource_Availability__c();
                rav.Name = 'Autogenerated';
                rav.Availability__c = 'Not Specified';
                rav.Possible_Date__c = pd.Id;
                rav.Resource_Assignment__c = ra.Id;
                insert rav;
                */
            }         
        }  
    }

}