/**************************************************************************************
// Name          : psaException
// Date          : April 8, 2015
// Description   : Allows custom exceptions to be thrown in Apex code
// Author        : CLD Partners
// Revisions     : 2015-04-08  Klassen  Initial version
//				 : 
***************************************************************************************/
public class psaException extends Exception {}